### ISSUE TITLE
Issue in scanning files under the subfolders

### ISSUE THREAD

**Issue by aarjavshah** [EXXETA/sonar-msgflow-plugin#11]
**Problem :** 
The message flow or subflow files listed under the subfolder/schema is not getting scanned in sonar.

**Rootcause :**
While adding the new file extension .map, I changed the logic in the sensor classes to list the messageflows and the subflows
_Previous Logic_
`for (InputFile inputFile : fs.inputFiles(fs.predicates().hasLanguage("msgflow"))) {`
_Changed Logic_
```

for (InputFile inputFile : fs.inputFiles(fs.predicates().matchesPathPatterns(MessageFlowPlugin.FLOW_PATH_PATTERNS))) {

//FLOW_PATH_PATTERNS = {"*.msgflow","*.subflow"};
```

**Replication:**
Create a subdirectory in the project directory. Copy and paste the same message flow file in the subdirectory. Once sonar report is generated, the issues in the file in the project directory will be reported. The same file in the subdirectory will not have issues.

**Possible Solution:**
Use the previous logic, followed by the condition check for file extension(this does not sound good to me). There should be a better way to do this using one of the Filepredicates functions. @ThomasPohl  Please suggest. 

Note : This issue would be generic for all the sensor classes.

**Comment by aarjavshah** [comment]
@ThomasPohl  Can you please help here?

**Comment by hitjay2002** [comment]
@ThomasPohl and @aarjavshah Hi, We are using this tool to run a review of IIB components and found this very useful. Can you please let us know when this change will be implemented to pick up .msgflow files from sub-directories?

**Comment by aarjavshah** [comment]
@hitjay2002
We have a temporary work around on this. If you want you can fork this repository and make those changes in your fork, build your version of the plug-in  and  use it for your component review. I'll help you there.
However, in the master branch of the plug-in, 
we will try to put in the permanent fix.

**Comment by rudrakshi** [comment]
@ThomasPohl  we are facing similar issue; the rule is not able to identify msgflows inside folders.
For example in following structure msgflow is not read:

abc
-pom.xml
-abc_app
  - gen
    -abc_MF.msgflow
  - subflow
     - func1_SF.subflow
     - func2_SF.subflow

**Comment by ThomasPohl** [comment]
Does this issue still occur after @aarjavshah 's fix?

**Comment by aarjavshah** [comment]
@ThomasPohl  I suggested the temporary work around on this. I did not push the code. I can push that if needed.

**Comment by rudrakshi** [comment]
If the msgflows within subfolders is not identified the plugin cannot check any rule. @ThomasPohl please help.

**Comment by ThomasPohl** [comment]
I have added a change to the file patterns. Please check if the plugin now parses flows in subdirectories.

**Comment by aarjavshah** [comment]
@ThomasPohl I checked for a sample project. It is scanning the files in the subdirectories.
