### ISSUE TITLE
Issue in Node level additional instances - SoapInputNode

### ISSUE THREAD

**Issue by aarjavshah** [EXXETA/sonar-msgflow-plugin#12]
Class cast exception.
Error : java.lang.String cannot be cast to java.lang.Integer.

I've identified the fix. I'll push the code changes for this fix and raise the pull request for the same.

**Comment by hitjay2002** [comment]
Can you please push the code for message flows to be taken from sub folder too (revert to old way). This will be really beneficial to us.

**Comment by aarjavshah** [comment]
@hitjay2002 
Please see my comment at
https://github.com/EXXETA/sonar-msgflow-plugin/issues/11

**Comment by aarjavshah** [comment]
With this change also pushed the bug fixes causing false positive in naming convention check and added Aggregate Reply node in the scope for checking multiple input terminals connected check.

**Comment by ThomasPohl** [comment]
Thanks @aarjavshah I will close this issue.
