### ISSUE TITLE
Issues in sonarqube start up with msgflow plugin 1.1.2

### ISSUE THREAD

**Issue by aarjavshah** [EXXETA/sonar-msgflow-plugin#15]
@ThomasPohl With the latest jar we are unable to start the sonarqube. I am using sonarqube 6.7.1.

PFB the error log for the same.

`2018.03.13 21:20:49 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2018.03.13 21:20:53 INFO  app[][o.e.p.PluginsService] no modules loaded
2018.03.13 21:20:53 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2018.03.13 21:21:18 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2018.03.13 21:21:18 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [C:\Users\user123\Desktop\O2\sonarqube-6.7.1]: C:\Program Files\Java\jre1.8.0_60\bin\java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=C:\Users\user123\Desktop\O2\sonarqube-6.7.1\temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -cp ./lib/common/*;./lib/server/*;C:\Users\user123\Desktop\O2\sonarqube-6.7.1\lib\jdbc\h2\h2-1.3.176.jar org.sonar.server.app.WebServer C:\Users\user123\Desktop\O2\sonarqube-6.7.1\temp\sq-process910263485050716448properties
2018.03.13 21:21:48 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2018.03.13 21:21:48 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2018.03.13 21:21:48 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped`

**Comment by ThomasPohl** [comment]
@aarjavshah  I didn't see that. Thanks for adding the issue.
