### ISSUE TITLE
problem in DSNSensor.java

### ISSUE THREAD

**Issue by aarjavshah** [EXXETA/sonar-msgflow-plugin#7]
pushed the wrong line here. @ThomasPohl help in correcting the line to the EXXETA master. Also added a check to handle the subflow files in NamingConventionSensor.java. I have pushed these changes to aarjavshah/master in the version 1.0

**_DSNSensor.java - line number 103_**
**pushed line :** 
String moduleNameFull = "esql://routine/generic#initialize.Main";//(String) msgFlowNode.getProperties().get("computeExpressionFull");

**Correct line :** 
String moduleNameFull = (String) msgFlowNode.getProperties().get("computeExpressionFull");

**_NamingConventionSensor.java - line number 102_**
**updated code:**
}else if((!fullPath.contains(".subflow")) && (fullPath.substring(fullPath.lastIndexOf(File.separator)+1, fullPath.indexOf(".msgflow")).matches("^[a-zA-Z]*(_App_v)[0-9]"))){

**Comment by ThomasPohl** [comment]
Great! I merged your changes.
