### ISSUE TITLE
Implementation Issues

### ISSUE THREAD

**Issue by aarjavshah** [EXXETA/sonar-msgflow-plugin#8]
**1. DSNSensor.java** 
    Problem : This class has the rule to raise the issue in case the data source property is specified without DB interaction. This rule does not specify the compute node name for which the issue is raised. 
    Solution : Updated the error message to include the same.
**2. IMSRequestNodeSensor.java**
    Problem : This class has the rule to raise an issue in case "Use Node Defined Properties" is set to true. The recommendation here is to use configurable service. However, the check was set in such way that it checks both the things (check box set to false and configurable service null/blank). This skips the IMS Request node with Use Node Defined Properties set as checked if the configurable service is specified. 
   Solution : Removed the additional check of configurable service null/blank.
**3. SoapRequestNodeSensor.java**
    Problem : This class has the rule to raise the issue in case the request timeout is set to _zero_. The check is placed to check the value as zero. However, in case default wait interval of 120 seconds is set on the node. This property is set as blank in the map. Which results in causing the number format exception.
    Solution : The additional check of not empty is placed to handle the default value.
4. MessageFlowRulesDefinition.java
    Updated the HTML description for the rule FilterNodeConnection to include additional comments for the user to understand the expectation.

@ThomasPohl Please assist in merging these changes.
I've pushed these changes in https://github.com/aarjavshah/sonar-msgflow-plugin fork. We are still testing all the rules. I'll update this if more issues are identified.

**Comment by aarjavshah** [comment]
I've created the pull request. However, I am still working on couple of rule changes. Let's plan to merge those in the new release along with these fixes as well. I'll make the changes in couple of days and provide the details as well.

**Comment by ThomasPohl** [comment]
Great. Just tell me when you are done, I will merge the pull request.

**Comment by aarjavshah** [comment]
This is also merged in the master branch.
